title = "Joshilog"
baseURL = "https://joshilog.com"
languageCode = "en-us"
theme = "ananke"
resourceDir = "resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Joshilog"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = "josh"
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  body_classes = "avenir bg-near-white"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/jmgloria07"
color = "#1DA1F2"

[[params.ananke_socials]]
name = "facebook"
url = "https://fb.me/jmgloria07"
color = "#3b5998"

[[params.ananke_socials]]
name = "instagram"
url = "https://ig.me/jmgloria07"
color = "#405DE6"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/jmgloria07"
color = "#4078c0"
